//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM_Tool_V5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GM_Tool_V5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001	Max HP Boost
        ///1002	Max MP Boost
        ///1003	HP Regen Boost
        ///1004	HP Recovery Boost
        ///1005	MP Regen Boost
        ///1006	MP Recovery Boost
        ///1007	P. Attack Boost
        ///1008	M. Power Boost
        ///1009	P. Defense Boost
        ///1010	Magical Defense Power increases
        ///1011	Attack Speed Boost
        ///1012	Cast Speed Boost
        ///1013	Move Speed Boost
        ///1014	Accuracy Boost
        ///1015	Evasion Boost
        ///1016	M. Accuracy Boost
        ///1017	M. Res increases
        ///1018	Crit Chance Boost
        ///1019	Crit Power Boost
        ///1021	Block Per Boost
        ///1051	Hidden Village Attack Power increases
        ///1052	Hid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string buffs {
            get {
                return ResourceManager.GetString("buffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xijezu.
        /// </summary>
        internal static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101331	Souleating Blade
        ///101531	Parasitic Blade
        ///101731	Flesheating Blade
        ///102331	Greatsword of Fury
        ///102531	Greatsword of Bloodrage
        ///102731	Greatsword of Obliteration
        ///103331	Twisted Barb
        ///103531	Shadowmage Barb
        ///103731	Dimensional Barb
        ///104331	Flameburst Spear
        ///104531	Mankiller Spear
        ///104731	Leon&apos;s Glory
        ///105331	Alloy Greataxe
        ///105531	Horizon&apos;s Edge
        ///105731	Hector&apos;s Greataxe
        ///106331	Smiter
        ///106531	Windbreaker
        ///106731	The Silencer
        ///107331	Kaia&apos;s Blessing
        ///107531	Hammer of Justice
        ///107731	Mace of Learning
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_white {
            get {
                object obj = ResourceManager.GetObject("logo_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize3 {
            get {
                object obj = ResourceManager.GetObject("Minimize3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	White Dragon Lv 1
        ///2	Bloodymos1
        ///3	Brain Slater1
        ///4	Clay Beast1
        ///5	Deva Priest
        ///6	Asura Priest
        ///7	Gaia Priest
        ///8	Ashmaw the Devourer
        ///9	Sand Lord Kynish
        ///10	Koala
        ///11	Lucky Koala
        ///12	Mystic Koala
        ///13	PrimalScream1
        ///14	Crustalino Test
        ///15	Bone Temple Guard
        ///16	Location of Crystal
        ///17	Unicorn Lv 3
        ///18	Dark Sachar
        ///19	White Wolf
        ///20	Cruelty Bashal
        ///21	Black Dragon
        ///22	Green Dragon
        ///23	Dun Fear
        ///24	ÅØ½ºÃ³Å×½ºÆ®
        ///25	Betrayal
        ///26	Liquidlust
        ///27	Bone Temple Guard
        ///28	Location of Crystal
        ///29	Guardian Angel
        ///30	In [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monster {
            get {
                return ResourceManager.GetString("monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 540001	Ent Card
        ///540002	Siren Card
        ///540003	White Dragon Card
        ///540004	Astarot Card
        ///540005	Red Pixie Card
        ///540006	Blue Pixie Card
        ///540009	Hawkman Card
        ///540010	Kentauros Card
        ///540011	Yeti Card
        ///540012	Salamander Card
        ///540013	Angel Card
        ///540014	Poultry Card
        ///540015	Tortus Card
        ///540016	Pantera Card
        ///540017	Young Ornitho
        ///540018	Skeleton Card
        ///540019	Orc Card
        ///540020	Lydian
        ///540021	Lydian (HV)
        ///540036	Cerberus Card
        ///540037	White Dragon Card
        ///540049	Mystic Koala Card&lt;Sealing card&gt;
        ///540052	Harpy Card
        ///540053	Wolf  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pets {
            get {
                return ResourceManager.GetString("pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Resize3 {
            get {
                object obj = ResourceManager.GetObject("Resize3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 152465	76951	Horizon
        ///151896	72599	Horizon Arena
        ///139369	73704	Witch
        ///132995	87096	Moonlight 1
        ///130842	79586	Moonlight 2
        ///155817	103724	Lost Mines 1
        ///152309	102886	Lost Mines 2
        ///117974	59119	Katan
        ///7363	7101	Laksy
        ///135876	156035	Fairy&apos;s Woods
        ///142086	132207	Siren Island
        ///138174	105965	Rondo
        ///159712	124736	Beginning of Marduka
        ///162624	131811	Mare Village
        ///211302	129971	Palmir Plateau 1
        ///211299	146193	Palmir Plateau 2
        ///103210	100366	CV1
        ///99757	103236	CV2
        ///154666	150287	City of Ruins
        ///83876	115913	Veiled Islan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string warplist {
            get {
                return ResourceManager.GetString("warplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Worldmap {
            get {
                object obj = ResourceManager.GetObject("Worldmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Xijezu {
            get {
                object obj = ResourceManager.GetObject("Xijezu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
